# Generated by Django 6.0.1 on 2026-01-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_embauche',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'embauche"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='poste',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Poste'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire (€)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='statut_employe',
            field=models.CharField(choices=[('actif', 'Actif'), ('conge', 'En congé'), ('renvoye', 'Renvoyé')], default='actif', max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('field_changed', models.CharField(blank=True, max_length=100, null=True)),
                ('old_value', models.CharField(blank=True, max_length=200, null=True)),
                ('new_value', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique Employé',
                'verbose_name_plural': 'Historique Employés',
            },
        ),
    ]
