# Generated by Django 6.0.1 on 2026-01-24 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_userprofile_date_embauche_userprofile_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChambreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chambres/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotel.chambre')),
            ],
            options={
                'verbose_name': 'Image Chambre',
                'verbose_name_plural': 'Images Chambres',
            },
        ),
    ]
