# Generated by Django 6.0.1 on 2026-01-29 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_chambreimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': "Catégorie d'inventaire",
                'verbose_name_plural': "Catégories d'inventaire",
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='employeehistory',
            options={},
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'article")),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantite_totale', models.PositiveIntegerField(default=0, verbose_name='Quantité totale')),
                ('quantite_disponible', models.PositiveIntegerField(default=0, verbose_name='Quantité disponible')),
                ('seuil_alerte', models.PositiveIntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon état'), ('use', 'Usé'), ('hors_service', 'Hors service')], default='neuf', max_length=20, verbose_name='État')),
                ('localisation_principale', models.CharField(choices=[('reception', 'Réception'), ('cuisine', 'Cuisine'), ('menage', 'Service de ménage'), ('maintenance', 'Maintenance'), ('depot', 'Dépôt'), ('autre', 'Autre')], default='depot', max_length=50, verbose_name='Localisation principale')),
                ('localisation_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='Détail de localisation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('derniere_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='hotel.inventorycategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': "Article d'inventaire",
                'verbose_name_plural': "Articles d'inventaire",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée en stock'), ('sortie', 'Sortie de stock'), ('affectation', 'Affectation'), ('retour', 'Retour en stock'), ('perte', 'Perte/Vol'), ('casse', 'Casse'), ('ajustement', "Ajustement d'inventaire")], max_length=20, verbose_name='Type de mouvement')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('date_mouvement', models.DateTimeField(auto_now_add=True, verbose_name='Date du mouvement')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='hotel.inventoryitem', verbose_name='Article')),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventaire_affecte', to='hotel.chambre', verbose_name='Chambre concernée')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_inventaire', to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_inventaire', to=settings.AUTH_USER_MODEL, verbose_name='Employé concerné')),
            ],
            options={
                'verbose_name': "Mouvement d'inventaire",
                'verbose_name_plural': "Mouvements d'inventaire",
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['nom'], name='hotel_inven_nom_ba20e1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['categorie'], name='hotel_inven_categor_daff3a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['etat'], name='hotel_inven_etat_145b60_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['localisation_principale'], name='hotel_inven_localis_202fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['article'], name='hotel_inven_article_b0b989_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['type_mouvement'], name='hotel_inven_type_mo_4f976d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['date_mouvement'], name='hotel_inven_date_mo_881ab2_idx'),
        ),
    ]
