# Generated by Django 6.0.1 on 2026-01-29 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_clientsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsettings',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='hotel.userprofile', verbose_name='Profil Utilisateur (paramètres)'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('sujet_autre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sujet personnalisé')),
                ('message', models.TextField(verbose_name='Message')),
                ('urgence', models.CharField(choices=[('normal', 'Normal - 24-48h'), ('urgent', 'Urgent - 4-8h'), ('critique', 'Critique - 1-2h')], default='normal', max_length=20, verbose_name="Niveau d'urgence")),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('repondu', 'Répondu'), ('resolu', 'Résolu'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut du message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('reponse', models.TextField(blank=True, null=True, verbose_name='Réponse')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('ip_client', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP du client')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Newsletter')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='hotel.client', verbose_name='Client')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_traites', to=settings.AUTH_USER_MODEL, verbose_name='Traité par')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
