# Generated by Django 6.0.1 on 2026-01-30 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_clientsettings_user_profile_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_charge', models.CharField(choices=[('maintenance', 'Maintenance'), ('inventaire', 'Achat inventaire'), ('personnel', 'Personnel externe'), ('energie', 'Énergie (électricité, eau)'), ('assurance', 'Assurance'), ('marketing', 'Marketing'), ('autre', 'Autre')], max_length=20, verbose_name='Type de charge')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('date_facture', models.DateField(verbose_name='Date de facture')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('fournisseur', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('reference_facture', models.CharField(blank=True, max_length=100, verbose_name='Référence facture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Charge comptable',
                'verbose_name_plural': 'Charges comptables',
                'ordering': ['-date_facture'],
                'indexes': [models.Index(fields=['type_charge'], name='hotel_charg_type_ch_7f8979_idx'), models.Index(fields=['statut'], name='hotel_charg_statut_d81582_idx'), models.Index(fields=['date_facture'], name='hotel_charg_date_fa_b4a8bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant HT')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Taux TVA (%)')),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TVA')),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant TTC')),
                ('statut', models.CharField(choices=[('payee', 'Payée'), ('en_attente', 'En attente'), ('remboursee', 'Remboursée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('moyen_paiement', models.CharField(blank=True, choices=[('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('mobile_money', 'Mobile Money')], max_length=20, verbose_name='Moyen de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='hotel.client', verbose_name='Client')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='hotel.reservation', verbose_name='Réservation associée')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['client'], name='hotel_factu_client__0791ea_idx'), models.Index(fields=['statut'], name='hotel_factu_statut_f69e22_idx'), models.Index(fields=['date_emission'], name='hotel_factu_date_em_534a32_idx')],
            },
        ),
        migrations.CreateModel(
            name='FichePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(verbose_name='Mois de paie')),
                ('numero_fiche', models.CharField(max_length=50, unique=True, verbose_name='Numéro de fiche')),
                ('salaire_brut', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire brut')),
                ('prime_anciennete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Prime d'ancienneté")),
                ('prime_performance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prime de performance')),
                ('prime_autres', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres primes')),
                ('cotisations_sociales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cotisations sociales')),
                ('impot_source', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Impôt à la source')),
                ('autres_retenu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres retenues')),
                ('total_primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total primes')),
                ('total_retenu', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total retenu')),
                ('salaire_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salaire net')),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('paye', 'Payé'), ('retard', 'En retard')], default='a_payer', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('moyen_paiement', models.CharField(blank=True, choices=[('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('cheque', 'Chèque')], max_length=20, verbose_name='Moyen de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_paie_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_paie', to=settings.AUTH_USER_MODEL, verbose_name='Employé')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-mois', 'employe'],
                'indexes': [models.Index(fields=['employe', 'mois'], name='hotel_fiche_employe_65277d_idx'), models.Index(fields=['statut'], name='hotel_fiche_statut_27724f_idx')],
                'unique_together': {('employe', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('type_maintenance', models.CharField(choices=[('corrective', 'Maintenance corrective'), ('preventive', 'Maintenance préventive'), ('urgence', "Maintenance d'urgence")], max_length=20, verbose_name='Type de maintenance')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('equipement', models.CharField(blank=True, max_length=200, verbose_name='Équipement concerné')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Date prévue')),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût réel')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='hotel.chambre', verbose_name='Chambre concernée')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut'], name='hotel_maint_statut_0f35e2_idx'), models.Index(fields=['priorite'], name='hotel_maint_priorit_eb90ce_idx'), models.Index(fields=['type_maintenance'], name='hotel_maint_type_ma_48cd5f_idx'), models.Index(fields=['date_creation'], name='hotel_maint_date_cr_63c5c0_idx')],
            },
        ),
    ]
