# Generated by Django 6.0.1 on 2026-01-30 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_chargecomptable_facture_fichepaie_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.BooleanField(default=True, verbose_name='Agent IA actif')),
                ('nom_agent', models.CharField(default='Assistant Hôtel', max_length=100, verbose_name="Nom de l'agent")),
                ('description', models.TextField(default='Assistant intelligent pour la gestion hôtelière', verbose_name='Description')),
                ('peut_repondre_clients', models.BooleanField(default=True, verbose_name='Peut répondre aux clients')),
                ('peut_consulter_donnees', models.BooleanField(default=True, verbose_name='Peut consulter les données')),
                ('peut_suggerer_actions', models.BooleanField(default=True, verbose_name='Peut suggérer des actions')),
                ('peut_generer_rapports', models.BooleanField(default=False, verbose_name='Peut générer des rapports')),
                ('max_requetes_jour', models.IntegerField(default=1000, verbose_name='Requêtes max par jour')),
                ('requetes_aujourd_hui', models.IntegerField(default=0, verbose_name="Requêtes aujourd'hui")),
                ('derniere_reinitialisation', models.DateField(auto_now_add=True, verbose_name='Dernière réinitialisation')),
                ('total_interactions', models.IntegerField(default=0, verbose_name='Total interactions')),
                ('derniere_interaction', models.DateTimeField(blank=True, null=True, verbose_name='Dernière interaction')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Configuration Agent IA',
                'verbose_name_plural': 'Configurations Agent IA',
            },
        ),
        migrations.CreateModel(
            name='AgentIAInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('page_contexte', models.CharField(blank=True, max_length=100, verbose_name='Page de contexte')),
                ('role_utilisateur', models.CharField(blank=True, max_length=20, verbose_name='Rôle utilisateur')),
                ('date_interaction', models.DateTimeField(auto_now_add=True, verbose_name='Date interaction')),
                ('duree_traitement', models.FloatField(blank=True, null=True, verbose_name='Durée traitement (s)')),
                ('utile', models.BooleanField(blank=True, null=True, verbose_name='Réponse utile')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='hotel.agentiaconfig')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction Agent IA',
                'verbose_name_plural': 'Interactions Agent IA',
                'ordering': ['-date_interaction'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('alerte_stock', 'Alerte de stock'), ('maintenance_urgente', 'Maintenance urgente'), ('message_client', 'Message client'), ('reservation_nouvelle', 'Nouvelle réservation'), ('facture_impayee', 'Facture impayée'), ('employe_absent', 'Employé absent'), ('systeme', 'Alerte système')], max_length=30, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('critique', 'Critique')], default='moyenne', max_length=20, verbose_name='Priorité')),
                ('lue', models.BooleanField(default=False, verbose_name='Lue')),
                ('traitee', models.BooleanField(default=False, verbose_name='Traitée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('article_inventaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hotel.inventoryitem')),
                ('destinataires', models.ManyToManyField(blank=True, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hotel.maintenance')),
                ('message_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hotel.contactmessage')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='hotel.reservation')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['type_notification'], name='hotel_notif_type_no_719987_idx'), models.Index(fields=['priorite'], name='hotel_notif_priorit_1077e4_idx'), models.Index(fields=['lue'], name='hotel_notif_lue_f85ff9_idx'), models.Index(fields=['date_creation'], name='hotel_notif_date_cr_9c0a89_idx')],
            },
        ),
    ]
