# Generated by assistant: Add default inventory categories
from django.db import migrations


def create_default_categories(apps, schema_editor):
    InventoryCategory = apps.get_model('hotel', 'InventoryCategory')
    default_names = [
        'Consommables',
        'Ménage',
        'Maintenance',
        'Réception',
        'Cuisine',
        'Dépôt',
        'Autre',
    ]
    for name in default_names:
        InventoryCategory.objects.get_or_create(nom=name)


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_agentiaconfig_agentiainteraction_notification'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_code=migrations.RunPython.noop),
    ]
